name: Build, Test and Deploy Docker Images

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest  # O runner do GitHub que estará executando os passos

    steps:
    # Passo 1: Check out do repositório
    - name: Check out repository
      uses: actions/checkout@v2  # Ação para fazer checkout do código

    # Passo 2: Set Docker Buildx para multi-plataforma
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    # Passo 3: Instalar Docker Compose
    - name: Install Docker Compose
      run: |
        sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
        sudo chmod +x /usr/local/bin/docker-compose

    # Passo 4: Login no Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}  # Seu Docker Hub Username
        password: ${{ secrets.DOCKER_PASSWORD }}  # Seu Docker Hub Token ou Password

    # Passo 5: Subir os containers com Docker Compose
    - name: Start services with Docker Compose
      run: |
        docker-compose -f docker-compose.yml up -d  # Inicializa os containers em segundo plano

    # Passo 6: Aguardar os containers estarem prontos (ex: PostgreSQL)
    - name: Wait for PostgreSQL to be ready
      run: |
        # Espera o PostgreSQL ficar disponível
        timeout 300 bash -c 'until pg_isready -h postgres-container -U postgres; do echo "Esperando o PostgreSQL..."; sleep 5; done;'

    # Passo 7: Construir a imagem da aplicação (caso seja necessário)
    - name: Build Docker image for the app
      run: |
        docker-compose build app  # Caso tenha uma construção específica para a aplicação

    # Passo 8: Empurrar a imagem para o Docker Hub (caso aplicável)
    - name: Push Docker image to Docker Hub
      run: |
        docker-compose push app  # Empurra a imagem da aplicação para o Docker Hub (ajuste conforme necessário)

    # Passo 9: Testes ou outras ações aqui (opcional)
    - name: Run tests
      run: |
        # Comandos para rodar testes ou outro processo de integração
        echo "Rodando testes..."

    # Passo 10: Parar os containers após o processo
    - name: Stop services
      run: |
        docker-compose down  # Para e remove os containers do Docker Compose
