name: Build, Test and Deploy Docker Images

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Start services with Docker Compose
      run: |
        docker-compose -f docker-compose.yml up -d
        docker ps  # Verifica se os containers estão rodando

    - name: Wait for PostgreSQL to be ready
      run: |
        until docker exec postgres-container pg_isready -U postgres; do
          echo "Waiting for PostgreSQL..."
          sleep 5
        done
        echo "PostgreSQL is ready!"

    - name: Build Docker image for the app
      run: |
        docker-compose build app

    - name: Push Docker image to Docker Hub
      run: |
        docker-compose push app

    - name: Run tests
      run: |
        pytest tests/

    - name: Stop services
      run: |
        docker-compose down
